<h2>PROJECT</h2>

<div>
	<p>E-den est une ville-monstre se nourrissant du travail des citoyens et des robots vivant « en-bas » afin d'entretenir la Bulle, le cerveau de cette cité. Toutes les richesses de cette société sont contenus dans la Bulle, paradis tournoyant lentement au dessus de la ville, où 4% de la population d' E-den demeure. Refusant l'acceptation ou même la vision des citoyens travaillant à leur bonheur en-bas, les hautes castes de E-den se sont emprisonnés dans cette Bulle où le luxe et l’opulence règnent et où les inégalités sont simplement oubliées. En-bas les conditions de vies se sont dégradés jusqu'à devenir  invivables ; ces quartiers livrés à eux même débordent de déchets toxiques, les citoyens désespérés s’entre-tuent régulièrement, et la milice robotique surveille l’obéissance de chaque citoyen.
	Dans une Cité où les inégalités sociales sont à leur paroxysme et où les castes les plus riches vivent emmurées dans une bulle, un groupe d'enfants des rues essaye de survivre. Vivant dans les bas-fonds de la Cité, asservie par la Bulle grâce à des robots violents, cette tribu d'enfants sauvages urbain côtoie un monde à la fois très pauvre mais aussi très technologique. Cachés de tous ils ne sortent qu'après le couvre-feu et sautent d'immeubles en immeubles grâce à leurs perches pour chercher de la nourriture, des matériaux ou d'autres enfants abandonnés à la faveur de la nuit. Ils sont très habiles et furtifs, mais aussi bricoleurs, ce qui leur permet d'accumuler une multitudes d'ordinateurs dans leur cachette. Pour ces enfants de la technologie, la programmation et le hacking est un jeu. Cela leur a permis avec le temps de contrôler certains mécanismes dans la Cité comme l'ouverture de porte ou le système d'éclairage des rues. Personne ne les connaît, seul quelques murmures racontent que leur proximité avec les déchets toxiques leur donne une courte espérance de vie mais leur confère aussi d'étranges capacités.
	Dans cette tribu, un leader se démarque, on l’appelle Cthulhu. Personne ne sait depuis quand il fait partie de la tribu mais le temps n'a pas l'air de faire son effet sur lui, ni même les maladies. Cthulhu est d'un tempérament calme, réfléchit et son sang paraît froid comme la Cité. Il analyse beaucoup ce qui l'entoure, ce qui l’entraîne souvent à trouver les solutions aux problèmes que personne n'avait encore relevé. C'est sans doute pour cela que les autres enfants le considèrent comme leur protecteur et le suive comme un meneur.</p>
	
</div>
	
